### ISSUE TITLE
Clarify README

### ISSUE THREAD

**Issue by Rundik** [fsouza/hls-rip#2]
I installed the package, but hls-rip command doesn't exist. I thing the installation guide should be more clean for those, who don't use go on regular basis

**Comment by fsouza** [comment]
Hi @Rundik, thanks for opening this issue. I'll add a note to the readme and will add some GitHub actions workflow to provide pre-compiled binaries too.

**Comment by fsouza** [comment]
hey @Rundik, I just pushed a note to the README. Do you think that's enough or should it have more info?
